version: "3"
services:
  service:
    image: "odkcentralcontainer:latest"
    build:
      context: .
      dockerfile: Dockerfile
    env_file: example.env
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
