echo "writing a new nginx configuration file.."
/bin/bash -c "envsubst '\$PORT' < /usr/share/nginx/odk.conf.template > /etc/nginx/conf.d/odk.conf"

CONFIG_PATH=/usr/odk/config/local.json
if [ ! -e "$CONFIG_PATH" ]
then
  echo "generating local service configuration.."

  # If DATABASE_URL is set, we've probably had configuration generated by 
  # Heroku and want to pipe the parts to the config.json file via the 
  # set of DATABASE__* variables
  if [ ! -e $DATABASE_URL ]
  then
    echo "using DATABASE_URL"
    export DATABASE__HOST=`node -e "const { getUrlPart } = require('./containerext/urlpart.js'); getUrlPart('${DATABASE_URL}','hostname');"`
    export DATABASE__USER=`node -e "const { getUrlPart } = require('./containerext/urlpart.js'); getUrlPart('${DATABASE_URL}','username');"`
    export DATABASE__PASSWORD=`node -e "const { getUrlPart } = require('./containerext/urlpart.js'); getUrlPart('${DATABASE_URL}','password');"`
    export DATABASE__DATABASE=`node -e "const { getUrlPart } = require('./containerext/urlpart.js'); getUrlPart('${DATABASE_URL}','pathname');"`
  fi

  # Write the config.json
  /bin/bash -c "envsubst < /usr/share/odk/config.json.template > $CONFIG_PATH"
fi

echo "running migrations.."
node -e 'const { withDatabase, migrate } = require("./lib/model/database"); withDatabase(require("config").get("default.database"))(migrate);'

# If DEFAULT_ADMIN_EMAIL is set, we want to run the bootstrapAdmin script to get the first user set up 
if [ ! -e "$DEFAULT_ADMIN_EMAIL" ]
then
  echo "found DEFAULT_ADMIN_EMAIL"
  node -e 'const { bootstrapAdmin } = require("./containerext/bootstrap.js"); bootstrapAdmin(require("config").get("default.database"), process.env.DEFAULT_ADMIN_EMAIL, process.env.DEFAULT_ADMIN_PASSWORD);'
  echo "done bootstrapping admin, remove DEFAULT_ADMIN_EMAIL and DEFAULT_ADMIN_PASSWORD from ENV for security"
fi

echo "starting cron.."
cron -f &

MEMTOT=$(vmstat -s | grep 'total memory' | awk '{ print $1 }')
if [ "$MEMTOT" -gt "1100000" ]
then
  WORKER_COUNT=4
else
  WORKER_COUNT=1
fi
echo "using $WORKER_COUNT worker(s) based on available memory ($MEMTOT).."

echo "starting nginx"
nginx

echo "starting pyxform"
waitress-serve --port=8080 --call main:app &

echo "starting server"
mkdir -p /var/log/odk
node node_modules/naught/lib/main.js start --remove-old-ipc true --worker-count $WORKER_COUNT --daemon-mode false --stdout - --stderr - lib/bin/run-server.js
